language: php
php:
- 5.5
sudo: false
before_script:
- composer self-update
- composer install --prefer-dist --no-interaction
before_install:
- openssl aes-256-cbc -K $encrypted_4ad563670d4c_key -iv $encrypted_4ad563670d4c_iv
  -in jf2-validator-df512ded97a5.json.enc -out jf2-validator-df512ded97a5.json -d
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: jf2-validator-df512ded97a5.json
  default: true
  project: jf2-validator
  on: master
